#!/bin/bash

TITLE="Power Menu"

lock=" Lock"
exit=" Exit Hyprland"
shutdown=" Poweroff"
reboot=" Reboot"

options="$lock\n$exit\n$shutdown\n$reboot"
option="$(echo -e "$options" | rofi -dmenu -p "$TITLE" -selected-row 0)"
echo $option

case $option in
$exit)
  hyprctl dispatch exit 1
  ;;
$lock)
  show-lock-screen
  ;;
$reboot)
  reboot
  ;;
$shutdown)
  poweroff
  ;;
esac
